export default {
  // FONT SIZES
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,

  // FONT WEIGHTS
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '600',
  FONT_WEIGHT_HEAVY: '800',

  // COLORS
  PRIMARY_COLOR: '#c4275d',
  SECONDARY_COLOR: '#ea6557',
  ALTERNATE_COLOR: '#24266c',
  ERROR_COLOR: 'red',
};
