export default {
  // FONT SIZES
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,

  // FONT WEIGHTS
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '600',
  FONT_WEIGHT_HEAVY: '800',

  // COLORS
  PRIMARY_COLOR: 'rgb(30, 147, 242)',
  SECONDARY_COLOR: 'rgb(238, 167, 2)',
  ERROR_COLOR: 'red',
};
